# This Dockerfile has been tested with image tag python3.8-nodejs16 and dependencies frozen in requirements.txt
# The python-nodejs image will need to be in sync and tested with any future upgrades to
# - Python
# - dependencies in requirements.txt (generated by 'pip freeze' command)
ARG BASE_CONTAINER=nikolaik/python-nodejs:python3.8-nodejs16
FROM $BASE_CONTAINER

LABEL maintainer="terra-test-runner-dashboard"

USER pn

RUN mkdir -p /home/pn/apps/testrunner

ADD  --chown=pn:pn test_runner_components /home/pn/apps/testrunner/test_runner_components
COPY --chown=pn:pn requirements.txt dashboard.py /home/pn/apps/testrunner/

WORKDIR /home/pn/apps/testrunner

# Install requirements.txt
# NB: During image build, you might get the following warining.
#  The warning can be ignored since we don't need seperate Python environments to run the app.
#  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour
#           with the system package manager. It is recommended to use a virtual environment instead:
#           https://pip.pypa.io/warnings/venv
USER root
RUN pip install -r requirements.txt

# Compile custom React.js components under test_runner_components/src/lib/components and convert them into Python modules
USER pn
WORKDIR /home/pn/apps/testrunner/test_runner_components
RUN npm install && npm run build

# Install custom dashboard libraries
USER root
WORKDIR /home/pn/apps/testrunner
RUN pip install ./test_runner_components/

USER pn
