name: Call sync component version workflow

on:
  push

jobs:
  call-sync-component-version:
    runs-on: ubuntu-latest

    steps:
      - name: Sync versions 58
        uses: DataBiosphere/terra-test-runner/.github/actions/sync-terra-services-version@QA-1612
        with:
          environment: dev
          token: ${{ secrets.BROADBOT_TOKEN }}

      - name: Echo terra version
        run: |
          echo $agora_appVersion
          echo $agora_chartVersion
